### ISSUE TITLE
Problem with restore_model

### ISSUE THREAD

**Issue by dparkins** [daniel-muthukrishna/DASH#1]
When I attempt to run dash on some spectra, I get the following error message:
`Traceback (most recent call last):
  File "check_type_with_dash.py", line 1, in <module>
    import dash
  File "/Users/uqdpark7/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/dash/__init__.py", line 3, in <module>
    from classify import Classify
  File "/Users/uqdpark7/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/dash/classify.py", line 7, in <module>
    from restore_model import LoadInputSpectra, BestTypesListSingleRedshift
ImportError: No module named restore_model
`

**Comment by dparkins** [comment]
Here is the python I used:
`import dash

filenames = []
filenames.append('DES16C3elb_C3_combined_161227_v10_b00.dat')
filenames.append('DES16X3eww_X3_combined_161225_v10_b00.dat')
filenames.append('DES16C1fgm_C1_combined_161226_v10_b00.dat')
filenames.append('DES16X1chc_X1_combined_161227_v10_b00.dat')
filenames.append('DES16X3dvb_X3_combined_161225_v10_b00.dat')
filenames.append('DES16X3enk_X3_combined_161225_v10_b00.dat')
filenames.append('DES16X2dzz_X2_combined_161226_v10_b00.dat')
filenames.append('DES16S2ffk_S2_combined_161227_v10_b00.dat')
filenames.append('DES16C2ege_C2_combined_161225_v10_b00.dat')
filenames.append('DES16S1ffb_S1_combined_161226_v10_b00.dat')
filenames.append('DES16X1few_X1_combined_161227_v10_b00.dat')

knownRedshifts = []
knownRedshifts.append(0.429)
knownRedshifts.append(0.329)
knownRedshifts.append(0.348)
knownRedshifts.append(0.445)
knownRedshifts.append(0.331)
knownRedshifts.append(0.164)
knownRedshifts.append(0.361)
knownRedshifts.append(0.325)
knownRedshifts.append(0.311)
knownRedshifts.append(0.043)
knownRedshifts.append(0.373)

classification = dash.Classify([filenames], [knownRedshifts])
print classification.list_best_matches(n=1)`

**Comment by daniel-muthukrishna** [comment]
The problem should be fixed no. Try 'pip install astrodash --upgrade' to get the latest version.

Also, a couple of notes on your script:
Your spectral files are in the incorrect order to match OzDES run028.
Sorry if my example usage was not clear (some proper documentation should be coming soon!), but Classify takes two lists as arguments (instead of a list of lists). I have corrected your above script below:

`import dash

filenames = []
filenames.append('DES16C3elb_C3_combined_161227_v10_b00.dat')
filenames.append('DES16X3dvb_X3_combined_161225_v10_b00.dat')
filenames.append('DES16C2ege_C2_combined_161225_v10_b00.dat')
filenames.append('DES16X3eww_X3_combined_161225_v10_b00.dat')
filenames.append('DES16X3enk_X3_combined_161225_v10_b00.dat')
filenames.append('DES16S1ffb_S1_combined_161226_v10_b00.dat')
filenames.append('DES16C1fgm_C1_combined_161226_v10_b00.dat')
filenames.append('DES16X2dzz_X2_combined_161226_v10_b00.dat')
filenames.append('DES16X1few_X1_combined_161227_v10_b00.dat')
filenames.append('DES16X1chc_X1_combined_161227_v10_b00.dat')
filenames.append('DES16S2ffk_S2_combined_161227_v10_b00.dat')


knownRedshifts = []
knownRedshifts.append(0.429)
knownRedshifts.append(0.329)
knownRedshifts.append(0.348)
knownRedshifts.append(0.445)
knownRedshifts.append(0.331)
knownRedshifts.append(0.164)
knownRedshifts.append(0.361)
knownRedshifts.append(0.325)
knownRedshifts.append(0.311)
knownRedshifts.append(0.043)
knownRedshifts.append(0.373)

classification = dash.Classify(filenames, knownRedshifts)
print classification.list_best_matches(n=1)`

On a side note, would you prefer to enter the filenames and redshifts in some other way? e.g. a list of two column tuples with (filename, redshift)?

**Comment by daniel-muthukrishna** [comment]
Update:
Unfortunately, DASH currently exceeds the limit allowed by PyPI, and as such pip installing does not include all the files. I have requested a larger size limit, and am also looking into alternative methods of hosting the large data. 
At this stage, you will have to download this GitHub project to classify supernovae. I will hopefully have a fix for 'pip' soon

**Comment by daniel-muthukrishna** [comment]
I've managed to find a work-around. The two big data files will now automatically download from this GitHub website (the first time you ever run DASH).

So 'pip install astrodash --upgrade' should work
Please let me know if it works on your computer

**Comment by dparkins** [comment]
Ok, now it seems to work fine. The first time I ran it, I got these messages:

> Downloading Trained Model...
> /Users/uqdpark7/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/dash/model_trainedAtZeroZ.ckpt
> Downloading Training Data files...
> /Users/uqdpark7/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/dash/type_age_atRedshiftZero.npz
> Downloading Model Parameters File...
> /Users/uqdpark7/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/dash/training_params.pickle
> Downloading Template Data files...
> /Users/uqdpark7/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/dash/templates.npz

This step took a while, but the second time it did not re-download. I suggest you add this to the install readme.

Anyway, works great now! Thanks very much.
